image:
  file: .gitpod.Dockerfile
tasks:
  - init: |
      stack build
      gp sync-done stack
    name: Build
  - init: |
      gp sync-await stack
      stack test
    name: Test
    openMode: split-right
vscode:
  extensions:
    - justusadam.language-haskell@2.6.0:CvYnp3YmQPTuto0m1di+1A==
    - hoovercj.haskell-linter@0.0.6:VpJluXvOyr9Iw7TIKg2Oyg==
    # - alanz.vscode-hie-server@0.0.28:j/YAJtXUGGbb8xSSz1i/CQ==
